name: Deploy to VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via Native SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # SSH directory setup
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Strict Host Checking ko bypass karke direct IPv6 connection
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@2400:adc5:175:5600:a00:27ff:fe8f:1f67 "cd /var/www/html && git pull origin main"