name: Deploy to VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}       # happy-shirts-tie.loca.lt
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Humne jo ED25519 ya RSA key lagayi thi
          port: 80                            # <-- SSH port ki jagah 80 ya 443 karein, kyunki localtunnel traffic HTTP port se aata hai
          script: |
            cd /var/www/html
            git pull origin main